services:
  salon-booking-system:
    # build:
    #   context: .  # กำหนดว่า context คือโฟลเดอร์ปัจจุบัน (รวม Dockerfile)
    image: thanapongc/project:repair
    env_file:
      - .env.production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: salon-booking-system
    ports:
      - "3002:3000"  # เชื่อมต่อพอร์ต 3002 ของเครื่องโฮสต์กับพอร์ต 3000 ในคอนเทนเนอร์
    networks:
      - salon-booking-system
    # depends_on:
    #   - nginx


networks:
  salon-booking-system:
    driver: bridge
